export const GEMSTONE_CONSTANTS = {
  CARAT: {
    LABEL_TH: 'น้ำหนักกะรัต',
    LABEL_EN: 'Carat Weight',
    UNIT: 'ct',
  },
  COLOR: {
    DIAMOND: {
      GRADES: ['D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'],
      DESC_TH: 'เกรดสีเพชร (น้ำ)',
    },
    COLORED_STONE: {
      HUES: [
        'Red',
        'Orangy Red',
        'Reddish Orange',
        'Orange',
        'Yellowish Orange',
        'Orangy Yellow',
        'Yellow',
        'Greenish Yellow',
        'Yellowish Green',
        'Green',
        'Bluish Green',
        'Greenish Blue',
        'Blue',
        'Violetish Blue',
        'Bluish Violet',
        'Violet',
        'Purple',
        'Reddish Purple',
        'Purplish Red',
        'Pink',
        'Orangy Pink',
        'Brownish Pink',
        'Pinkish Orange (Padparadscha)',
        'Pigeon Blood Red',
        'Royal Blue',
        'Cornflower Blue',
        'Emerald Green',
        'Mint Green',
        'Teal',
        'Champagne',
        'Cognac',
        'Brown',
        'Reddish Brown',
        'Brownish Red',
        'Colorless (White)',
        'Black',
        'Bi-color',
        'Watermelon',
        'Color-change',
      ],
      TONE: ['Very Light', 'Light', 'Medium Light', 'Medium', 'Medium Dark', 'Dark', 'Very Dark'],
      SATURATION: ['Vivid', 'Strong', 'Moderately Strong', 'Moderate', 'Slightly Grayish', 'Grayish'],
    },
  },
  CLARITY: {
    DIAMOND: ['FL', 'IF', 'VVS1', 'VVS2', 'VS1', 'VS2', 'SI1', 'SI2'],
    COLORED_STONE: {
      TYPE_1: 'Eye Clean (มองด้วยตาเปล่าไม่เห็นตำหนิ)',
      TYPE_2: 'Slightly Included (มีตำหนิตามธรรมชาติเล็กน้อย)',
      TYPE_3: 'Prominently Included (มีตำหนิเป็นปกติ)',
    },
  },
  CUT: {
    SHAPES: ['Round', 'Princess', 'Emerald', 'Cushion', 'Oval', 'Pear', 'Heart'],
    GRADING: ['Excellent', 'Very Good', 'Good', 'Fair'],
  },
  TREATMENT: {
    DIAMOND: ['Natural', 'Lab Grown (CVD/HPHT)'],
    COLORED_STONE: [
      { key: 'N', label_th: 'ไม่ผ่านการเผา (Unheated)', value: 'No Heat' },
      { key: 'H', label_th: 'เผาเก่า (Heated)', value: 'Heat' },
      { key: 'H(a/b)', label_th: 'เผาใหม่ (Heated with Residue)', value: 'Flux/Lead Glass' },
    ],
  },
  ORIGIN: {
    LABEL_TH: 'แหล่งกำเนิด',
    SOURCES: [
      'Burma (Myanmar)',
      'Sri Lanka (Ceylon)',
      'Thailand (Kanchanaburi/Chanthaburi)',
      'Madagascar',
      'Colombia',
      'Brazil',
      'Mozambique',
      'Tanzania',
      'Zambia',
      'Ethiopia',
      'Kenya',
      'Nigeria',
      'Afghanistan',
      'Pakistan',
      'Vietnam',
      'Australia',
      'Russia',
      'USA',
    ],
  },
} as const
