/** Mission Control command metadata ownership. */
import type { CommandMetadataDependencies } from './mission-control-command-metadata-deps.ts'

export function missionControlPrimaryCommands(dependencies: CommandMetadataDependencies) {
  const { contract, positional, stdinInput, flag, nextAction } = dependencies
  return {
  'bemoat:mission-control:authorize-founder': contract({
    command: 'bemoat:mission-control:authorize-founder',
    tier: 'A',
    entrypoint: 'scripts/mission-control-authorize-founder.mjs',
    purpose: 'Record an immutable Founder merge authorization.',
    operation: 'Validate Founder identity, exact head, policy source, and protected base, and project an immutable merge authorization and receipt.',
    accepted_pre_states: ['ELIGIBLE_FOR_FOUNDER_REVIEW', 'STANDARD_NON_MANAGED_ELIGIBLE'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Task Issue number; the live declaration determines managed or STANDARD/non-managed eligibility.'),
      flag('scope', '--scope <scope>', 'enum', 'Authorization scope.', ['merge'], true),
    ],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
    ],
    trusted_derived_values: ['authenticated actor identity', 'trusted Founder logins', 'live PR/base/head/policy evidence', 'branch reservation evidence'],
    required_evidence: [
      'Exact head, base, and policy identity from managed state or trusted live STANDARD/non-managed evidence.',
      'Authenticated GitHub actor must be a trusted Founder.',
      'Live protected main ref.',
      'For STANDARD/non-managed Issues: merged-policy eligibility, one active exact-target REVIEW_VERDICT, and its immutable comment ID.',
    ],
    reads: ['Task/PR/state', 'live protected main', 'BEMOAT_FOUNDER_LOGINS action variable'],
    writes: ['immutable authorization comment', 'immutable receipt comment', 'coordination lease comments'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'An identical retry is allowed only when the same exact authorization comment and receipt are already durable.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        condition: 'Managed Task Issue with valid managed state.',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:merge', 'The authorization is ready for the merge completion bundle.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        condition: 'Managed Task Issue with valid managed state.',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:merge', 'The identical authorization is already durable.'),
      },
      {
        classification: 'SUCCESS',
        condition: 'Explicit STANDARD/non-managed eligibility with no managed state.',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:merge-standard', 'The authorization is ready for the disjoint STANDARD/non-managed merge completion transport.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        condition: 'Explicit STANDARD/non-managed eligibility with no managed state.',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:merge-standard', 'The identical STANDARD/non-managed authorization is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Authorize a merge for a Task Issue.',
        argv: ['284', '--scope', 'merge', '--repo', 'boat1994/bemoat-web-starter'],
      },
    ],
    parser_owner: 'scripts/mission-control-authorize-founder.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:authorize-founder -- --help --json',
    last_validation_before_mutation: 'Re-read the Task Issue, policy lineage, protected base, and existing authorization comments immediately before the leased/CAS write.',
    post_write_readback: 'Re-read the Issue comments and confirm the projected immutable authorization identity and receipt.',
    legacy_classification_map: {
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:dispatch': contract({
    command: 'bemoat:mission-control:dispatch',
    tier: 'A',
    entrypoint: 'scripts/mission-control-dispatch.mjs',
    purpose: 'Claim the next Mission Control delivery or authorized correction.',
    operation: 'Validate HANDOFF evidence and project one leased dispatch transition.',
    accepted_pre_states: ['READY', 'FOUNDER_AUTHORIZED_CORRECTION'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
      stdinInput('handoff_body', 'Canonical HANDOFF body when --body-file is not used.'),
    ],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
      flag('body_file', '--body-file <path>', 'path', 'Read the HANDOFF body from this file instead of stdin.'),
      flag('founder_correction', '--founder-correction', 'boolean', 'Consume the exact Founder correction authorization route.'),
      flag('workflow_mode', '--workflow-mode <mode>', 'enum', 'Explicit workflow mode.', ['planning_no_pr', 'implementation_pr']),
      flag('planning_base_sha', '--planning-base-sha <full-sha>', 'full_sha', 'Exact planning authorization base SHA.'),
    ],
    trusted_derived_values: ['workflow identity', 'repository-owned policy version and source SHA', 'branch reservation evidence'],
    required_evidence: [
      'Task Issue state and active-task identity.',
      'Canonical HANDOFF evidence and immutable transition identity.',
      'Workflow mode and planning lineage when applicable.',
      'Branch reservation evidence for the selected operation.',
    ],
    reads: ['Issue/state/comments/PR', 'HANDOFF body', 'branch reservation evidence'],
    writes: ['HANDOFF comment', 'leased/CAS Issue state', 'temporary reservation ref with cleanup'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'An identical retry is allowed only when the same HANDOFF transition identity is already projected.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMMAND', 'bemoat:agent:delivery', 'The dispatch claim is ready for one delivery RESULT.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The identical dispatch claim is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Dispatch a canonical HANDOFF.',
        argv: ['284', '--repo', 'boat1994/bemoat-web-starter', '--body-file', './handoff.md'],
      },
    ],
    parser_owner: 'scripts/mission-control-dispatch.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:dispatch -- --help --json',
    last_validation_before_mutation: 'Re-read the Task Issue, HANDOFF evidence, policy lineage, and branch reservation immediately before the leased/CAS write.',
    post_write_readback: 'Re-read the Issue, comments, and reservation cleanup state and confirm the projected dispatch identity.',
    legacy_classification_map: {
      DISPATCHED: 'SUCCESS',
      DISPATCHED_FOUNDER_AUTHORIZED_CORRECTION: 'SUCCESS',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:merge': contract({
    command: 'bemoat:mission-control:merge',
    tier: 'A',
    entrypoint: 'scripts/mission-control-merge.mjs',
    purpose: 'Execute an existing Founder-authorized merge completion bundle.',
    operation: 'Verify reviewed head, authorization, checks, merge, and terminal projections.',
    accepted_pre_states: ['ELIGIBLE_FOR_FOUNDER_REVIEW', 'DONE'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.', [], true),
      flag('authorization_comment', '--authorization-comment <id>', 'positive_integer', 'Immutable Founder merge authorization comment.', [], true),
    ],
    trusted_derived_values: ['live PR/base/head/check evidence', 'Founder identity configuration', 'campaign projection evidence'],
    required_evidence: [
      'Founder merge authorization bound to the reviewed head.',
      'Exact PR/base/check and protected-head evidence.',
      'Task Issue and campaign completion projections.',
    ],
    reads: ['Founder authorization', 'Task/PR/comments/checks/base/policy/campaign'],
    writes: ['ready/merge state', 'terminal RESULT comment', 'Issue close/state', 'campaign projection'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A DONE task with the exact verified merge-completion bundle returns NO_OP_IDENTICAL_RETRY and performs no new mutation.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The Founder-authorized merge completion bundle is durable.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The identical merge completion is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Execute a Founder-authorized merge.',
        argv: ['284', '--repo', 'boat1994/bemoat-web-starter', '--authorization-comment', '12345'],
      },
    ],
    parser_owner: 'scripts/mission-control-merge.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:merge -- --help --json',
    last_validation_before_mutation: 'Re-read authorization, reviewed head, protected base, checks, Task state, and campaign evidence immediately before merge/CAS operations.',
    post_write_readback: 'Re-read PR, Task Issue, comments, and campaign projection and confirm the complete DONE bundle.',
    legacy_classification_map: {
      DONE: 'SUCCESS',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:merge-standard': contract({
    command: 'bemoat:mission-control:merge-standard',
    tier: 'A',
    entrypoint: 'scripts/mission-control-merge-standard.mjs',
    purpose: 'Execute one Founder-authorized STANDARD/non-managed merge completion.',
    operation: 'Derive explicit STANDARD eligibility, verify one exact immutable review/Founder evidence tuple, merge the exact PR head, and prove the protected-base readback without creating managed state.',
    accepted_pre_states: ['STANDARD_NON_MANAGED_ELIGIBLE'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'STANDARD/non-managed Task Issue number.'),
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Issue.', [], true),
      flag('authorization_comment', '--authorization-comment <id>', 'positive_integer', 'Immutable Founder merge authorization comment.', [], true),
    ],
    trusted_derived_values: [
      'explicit STANDARD profile from merged policy and live Issue declarations',
      'live PR/base/head/check/mergeability evidence',
      'one active non-superseded REVIEW_VERDICT and immutable comment ID',
      'trusted policy path/version/blob SHA and protected-base commit SHA',
    ],
    required_evidence: [
      'No managed-state marker and explicit policy-compatible STANDARD declaration.',
      'Exact repository/Issue/PR/base/head binding.',
      'Exact-head CI and CI (starter strict) success.',
      'One canonical active non-superseded REVIEW_VERDICT bound by immutable comment ID.',
      'Founder authorization and receipt bound to the separate policy blob and protected-base identities.',
    ],
    reads: ['Issue/body/comments', 'PR/head/base/mergeability/checks', 'Founder authorization/receipt', 'protected main', 'merged policy'],
    writes: ['exact authorized PR merge only'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    stop_classifications: ['INVALID_INVOCATION', 'UNSUPPORTED_PRE_STATE', 'STATE_CONFLICT', 'AUTHORITY_CONFLICT', 'HEAD_DRIFT', 'BLOCKED_EXTERNAL', 'EVIDENCE_CONFLICT', 'AMBIGUOUS_RESULT', 'INTERNAL_ERROR'],
    stop_conditions: ['Stop before merge on managed, ambiguous, stale, competing, malformed, mismatched, or unavailable evidence; never blind-retry an ambiguous write.'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'Return NO_OP_IDENTICAL_RETRY only after the same exact PR/head merge and protected-base readback are durably proven.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The exact STANDARD/non-managed merge completion is durably verified.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The identical STANDARD/non-managed merge completion is already durably verified.'),
      },
    ],
    examples: [
      {
        description: 'Execute a STANDARD/non-managed Founder-authorized merge.',
        argv: ['379', '--repo', 'boat1994/bemoat-web-starter', '--authorization-comment', '12345'],
      },
    ],
    parser_owner: 'scripts/mission-control-merge-standard.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:merge-standard -- --help --json',
    last_validation_before_mutation: 'Re-read the live Issue declaration, protected main/policy, PR/head/base/CI/mergeability, selected REVIEW_VERDICT, and Founder authorization immediately before exact-head merge.',
    post_write_readback: 'Re-read the PR and protected main and confirm the exact merge commit is present on the protected base; do not mutate managed Issue state.',
    legacy_classification_map: {
      MERGED: 'SUCCESS',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:reconcile': contract({
    command: 'bemoat:mission-control:reconcile',
    tier: 'A',
    entrypoint: 'scripts/mission-control-reconcile.mjs',
    purpose: 'Repair routing-only Mission Control projection drift.',
    operation: 'Classify authoritative evidence and apply only a leased/CAS routing projection repair.',
    accepted_pre_states: [
      'READY',
      'IN_PROGRESS',
      'AWAITING_REVIEW_1',
      'CORRECTION_REQUIRED_1',
      'AWAITING_REVIEW_2',
      'CORRECTION_REQUIRED_2',
      'AWAITING_REVIEW_3',
      'FOUNDER_AUTHORIZED_CORRECTION',
      'BLOCKED_FOR_FOUNDER_DECISION',
      'ELIGIBLE_FOR_FOUNDER_REVIEW',
      'DONE',
      'BLOCKED_EXTERNAL',
      'STATE_CONFLICT',
      'STATE_MIGRATION_REQUIRED',
    ],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
    ],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
    ],
    trusted_derived_values: ['canonical transport ownership', 'live evidence identity', 'lease/CAS holder identity'],
    required_evidence: ['Authoritative live evidence proves routing-only projection drift after a failed canonical transport.'],
    reads: ['Task/PR/comments/state/terminal evidence'],
    writes: ['routing-only Issue state projection via lease/CAS'],
    success_classifications: [
      'SUCCESS',
      'NO_OP_IDENTICAL_RETRY',
    ],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is identical only when the authoritative evidence and routing projection already agree.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The routing-only projection repair is verified.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'No routing projection repair remains necessary.'),
      },
    ],
    examples: [{ description: 'Reconcile routing-only projection drift.', argv: ['284', '--repo', 'boat1994/bemoat-web-starter'] }],
    parser_owner: 'scripts/mission-control-reconcile.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:reconcile -- --help --json',
    last_validation_before_mutation: 'Re-read the authoritative evidence and Task Issue body immediately before the routing-only lease/CAS write.',
    post_write_readback: 'Re-read the Task Issue and confirm only the permitted routing projection changed.',
    legacy_classification_map: {
      RECONCILED: 'SUCCESS',
      BOOKKEEPING_REPAIR: 'SUCCESS',
      TERMINAL_REPAIR: 'SUCCESS',
      DISPATCHED: 'SUCCESS',
      REVIEWED: 'SUCCESS',
      RECOVERABLE_ROUTING_DRIFT: 'AMBIGUOUS_RESULT',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:recover-review': contract({
    command: 'bemoat:mission-control:recover-review',
    tier: 'A',
    entrypoint: 'scripts/mission-control-recover-review.mjs',
    purpose: 'Quarantine only the exact approved #274/#275 raw-review incident.',
    operation: 'Verify the pinned incident tuple and project its proven Review 2 result.',
    accepted_pre_states: ['AWAITING_REVIEW_2'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Quarantined incident Task Issue number.'),
      flag('repository', '--repo <owner/repository>', 'repository', 'Exact starter repository.', [], true),
      flag('expected_pr', '--expected-pr <number>', 'positive_integer', 'Exact incident Pull Request number.', [], true),
      flag('expected_base', '--expected-base <branch>', 'string', 'Exact protected base branch.', [], true),
      flag('expected_state', '--expected-state <state>', 'enum', 'Expected incident managed state.', ['AWAITING_REVIEW_2'], true),
      flag('expected_head', '--expected-head <full-sha>', 'full_sha', 'Exact incident PR head.', [], true),
      flag('expected_review_cycle', '--expected-review-cycle <number>', 'positive_integer', 'Expected managed review cycle.', [], true),
      flag('expected_full_review_count', '--expected-full-review-count <number>', 'positive_integer', 'Expected full-review count.', [], true),
      flag('review_type', '--review-type <type>', 'enum', 'Exact recovery review type.', ['delta'], true),
      flag('issue_source_comment', '--issue-source-comment <id>', 'positive_integer', 'Pinned Task Issue source comment.', [], true),
      flag('pr_source_comment', '--pr-source-comment <id>', 'positive_integer', 'Pinned PR source comment.', [], true),
      flag('original_review_comment', '--original-review-comment <id>', 'positive_integer', 'Pinned original review comment.', [], true),
      flag('correction_result_comment', '--correction-result-comment <id>', 'positive_integer', 'Pinned correction RESULT comment.', [], true),
      flag('body_file', '--body-file <path>', 'path', 'Read recovery review body from this file.', [], true),
    ],
    required_evidence: [
      'Pinned #274/#275 repository, Issue, PR, base, state, head, and comment tuple.',
      'Executing checkout and policy identity.',
      'Quarantined raw-review evidence with no ordinary-review ownership.',
    ],
    reads: ['pinned policy/source/checkout', 'Task/PR/comments/checks'],
    writes: ['one quarantined REVIEW_VERDICT comment', 'leased/CAS state projection'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is identical only when the same quarantined recovery evidence and projection are already durable.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The exact incident recovery projection is verified.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The exact incident recovery projection is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Run the quarantined incident recovery route.',
        argv: [
          '274',
          '--repo',
          'boat1994/bemoat-web-starter',
          '--expected-pr',
          '275',
          '--expected-base',
          'main',
          '--expected-state',
          'AWAITING_REVIEW_2',
          '--expected-head',
          '<full-sha>',
          '--expected-review-cycle',
          '1',
          '--expected-full-review-count',
          '1',
          '--review-type',
          'delta',
          '--issue-source-comment',
          '<task-issue-comment-id>',
          '--pr-source-comment',
          '<pr-source-comment-id>',
          '--original-review-comment',
          '<original-review-comment-id>',
          '--correction-result-comment',
          '<correction-result-comment-id>',
          '--body-file',
          './review.md',
        ],
      },
    ],
    parser_owner: 'scripts/mission-control/workflows/recover-review.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:recover-review -- --help --json',
    last_validation_before_mutation: 'Verify the complete pinned #274/#275 tuple and quarantine boundary immediately before the state/comment writes.',
    post_write_readback: 'Re-read the quarantined comment and managed state and confirm no ordinary REVIEW_VERDICT path was used.',
    legacy_classification_map: {
      RECOVERED: 'SUCCESS',
      RECOVERABLE_ROUTING_DRIFT: 'AMBIGUOUS_RESULT',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),

  }
}
