/** Mission Control routing policy ownership. */
export const ALL_MUTATING_COMMANDS: string[] = [
  'bemoat:boilerplate:sync',
  'bemoat:hooks:install',
  'bemoat:issue:comment',
  'bemoat:mission-control:authorize-founder',
  'bemoat:mission-control:task-bootstrap',
]


type RouteParams = {
  route_key: string
  observed_state: string | null
  evidence_case: string
  required_evidence_condition: string
  forbidden_evidence_condition: string
  permitted_operation: string | null
  canonical_command: string | null
  required_review_type: string | null
  expected_post_state_or_gate: string
  prohibited_commands?: string[]
  decision: string
  stop_condition?: string | null
}

function route({
  route_key,
  observed_state,
  evidence_case,
  required_evidence_condition,
  forbidden_evidence_condition,
  permitted_operation,
  canonical_command,
  required_review_type,
  expected_post_state_or_gate,
  prohibited_commands = [],
  decision,
  stop_condition = null,
}: RouteParams) {
  return {
    route_key,
    observed_state,
    evidence_case,
    required_evidence_condition,
    forbidden_evidence_condition,
    permitted_operation,
    canonical_command,
    required_review_type,
    expected_post_state_or_gate,
    prohibited_commands,
    decision,
    stop_condition,
  }
}

export function missionControlPrimaryRoutes() {
  return [
  route({
    route_key: 'no-task/founder-authorization-recording',
    observed_state: null,
    evidence_case: 'Founder authorization is present in the execution context but no immutable repository-owned comment is durable',
    required_evidence_condition: 'Authenticated GitHub actor is a trusted Founder and live protected-base/policy/Issue evidence is complete.',
    forbidden_evidence_condition: 'Caller-supplied identity, placeholder body, comment edit, conflicting comment, or uncertain POST/readback.',
    permitted_operation: 'Record one final raw JSON Founder authorization body and verify its returned immutable ID/readback.',
    canonical_command: 'bemoat:mission-control:authorize-founder',
    required_review_type: null,
    expected_post_state_or_gate: 'Durable immutable Founder authorization evidence',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'no-task/exact-task-bootstrap-founder-authorization-workflow-tuple',
    observed_state: null,
    evidence_case: 'exact-task-bootstrap-founder-authorization-workflow-tuple',
    required_evidence_condition: 'Signed Founder authorization, trusted Actions workflow identity, public key, and campaign/PR tuple are complete.',
    forbidden_evidence_condition: 'Any missing, stale, competing, or conflicting bootstrap identity/evidence.',
    permitted_operation: 'Create and attest the Task Issue.',
    canonical_command: 'bemoat:mission-control:task-bootstrap',
    required_review_type: null,
    expected_post_state_or_gate: 'READY',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'READY/retired-stateful-dispatch',
    observed_state: 'READY',
    evidence_case: 'retired-stateful-dispatch',
    required_evidence_condition: 'A historical READY projection or HANDOFF is encountered after the stateful dispatch transport has been retired.',
    forbidden_evidence_condition: 'Any attempt to infer a replacement stateful delivery command or mutate the historical projection.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical dispatch transport is retired and no replacement stateful transport is authorized.',
  }),
  route({
    route_key: 'IN_PROGRESS/retired-delivery-coordinator',
    observed_state: 'IN_PROGRESS',
    evidence_case: 'retired-delivery-coordinator',
    required_evidence_condition: 'The historical IN_PROGRESS projection is encountered after the delivery coordinator has been retired.',
    forbidden_evidence_condition: 'Any attempt to infer a replacement stateful delivery command or mutate the historical projection.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical delivery coordinator is retired and no replacement stateful transport is authorized.',
  }),
  route({
    route_key: 'AWAITING_REVIEW_1/retired-managed-review-writer',
    observed_state: 'AWAITING_REVIEW_1',
    evidence_case: 'retired-managed-review-writer',
    required_evidence_condition: 'A historical AWAITING_REVIEW_1 projection is encountered after the managed review writer has been retired.',
    forbidden_evidence_condition: 'Any attempt to publish managed review state or mutate review counters.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical managed review writer is retired and no replacement review transport is authorized.',
  }),
  route({
    route_key: 'CORRECTION_REQUIRED_1/founder-authorized-finding-adoption',
    observed_state: 'CORRECTION_REQUIRED_1',
    evidence_case: 'founder-authorized-finding-adoption',
    required_evidence_condition: 'An immutable Founder adopt-finding authorization and predecessor correction contract are complete for the live CORRECTION_REQUIRED_1 head.',
    forbidden_evidence_condition: 'Caller-supplied findings, superseded authorization, competing adoption comments, or head/base drift.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_1 with reconciled active correction-contract identity',
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; no finding-adoption transport is authorized.',
  }),
  route({
    route_key: 'AWAITING_REVIEW_2/retired-managed-review-writer',
    observed_state: 'AWAITING_REVIEW_2',
    evidence_case: 'retired-managed-review-writer',
    required_evidence_condition: 'A historical AWAITING_REVIEW_2 projection is encountered after the managed review writer has been retired.',
    forbidden_evidence_condition: 'Any attempt to publish managed review state or mutate review counters.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical managed review writer is retired and no replacement review transport is authorized.',
  }),
  route({
    route_key: 'CORRECTION_REQUIRED_2/founder-authorized-finding-adoption',
    observed_state: 'CORRECTION_REQUIRED_2',
    evidence_case: 'founder-authorized-finding-adoption',
    required_evidence_condition: 'An immutable Founder adopt-finding authorization and predecessor correction contract are complete for the live CORRECTION_REQUIRED_2 head.',
    forbidden_evidence_condition: 'Caller-supplied findings, superseded authorization, competing adoption comments, or head/base drift.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_2 with reconciled active correction-contract identity',
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; no finding-adoption transport is authorized.',
  }),
  route({
    route_key: 'AWAITING_REVIEW_3/retired-managed-review-writer',
    observed_state: 'AWAITING_REVIEW_3',
    evidence_case: 'retired-managed-review-writer',
    required_evidence_condition: 'A historical AWAITING_REVIEW_3 projection is encountered after the managed review writer has been retired.',
    forbidden_evidence_condition: 'Any attempt to publish managed review state or mutate review counters.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical managed review writer is retired and no replacement review transport is authorized.',
  }),
  route({
    route_key: 'FOUNDER_AUTHORIZED_CORRECTION/unconsumed-exact-authorization',
    observed_state: 'FOUNDER_AUTHORIZED_CORRECTION',
    evidence_case: 'unconsumed-exact-authorization',
    required_evidence_condition: 'One unconsumed exact Founder correction authorization binds the current head and bounded scope.',
    forbidden_evidence_condition: 'Consumed, superseded, competing, or head-drifted authorization.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical dispatch transport is retired and no replacement stateful transport is authorized.',
  }),
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/exact-merge-authorization-recording',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'exact-merge-authorization-recording',
    required_evidence_condition: 'A trusted Founder provides authorization for the complete repository/Task/PR/base and reviewed head.',
    forbidden_evidence_condition: 'Head drift, duplicate authorization, competing authority, or agent invocation.',
    permitted_operation: 'Record an immutable Founder merge authorization.',
    canonical_command: 'bemoat:mission-control:authorize-founder',
    required_review_type: null,
    expected_post_state_or_gate: 'ELIGIBLE_FOR_FOUNDER_REVIEW with an immutable merge authorization and receipt',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'BLOCKED_FOR_FOUNDER_DECISION/missing-named-authorization',
    observed_state: 'BLOCKED_FOR_FOUNDER_DECISION',
    evidence_case: 'missing-named-authorization',
    required_evidence_condition: 'The blocking evidence is present but the exact named Founder authorization is absent.',
    forbidden_evidence_condition: 'Any agent-mutation authorization or competing authority.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Wait for the exact named Founder authorization; no agent mutation is permitted.',
  }),
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/missing-merge-authorization',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'missing-merge-authorization',
    required_evidence_condition: 'An eligible review result is complete but merge authorization is absent.',
    forbidden_evidence_condition: 'Any inferred, stale, competing, or non-Founder merge authority.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Wait for explicit Founder merge or reopen authorization; no agent mutation is permitted.',
  }),
  route({
    route_key: 'NOT_STATEFUL/retired-standard-merge-wrapper',
    observed_state: 'NOT_STATEFUL',
    evidence_case: 'retired-standard-merge-wrapper',
    required_evidence_condition: 'A historical STANDARD/non-managed merge-wrapper route is encountered after the custom merge transport has been retired.',
    forbidden_evidence_condition: 'Any attempt to invoke or replace the retired custom merge wrapper.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — native GitHub merge authority only',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; Context must reconstruct any ordinary native GitHub merge authority and evidence.',
  }),
  ]
}
