/** Mission Control command metadata ownership. */
import type { CommandMetadataDependencies } from './mission-control-command-metadata-deps.ts'

export function missionControlReviewCommands(dependencies: CommandMetadataDependencies) {
  const { contract, positional, flag, environment, nextAction } = dependencies
  return {
  'bemoat:mission-control:reopen': contract({
    command: 'bemoat:mission-control:reopen',
    tier: 'A',
    entrypoint: 'scripts/mission-control-reopen.mjs',
    purpose: 'Project the exact Founder-authorized #285 reopen correction route.',
    operation: 'Verify old/new heads and Founder authorization, then project bounded correction state.',
    accepted_pre_states: ['ELIGIBLE_FOR_FOUNDER_REVIEW'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.', [], true),
      flag('expected_pr', '--expected-pr <number>', 'positive_integer', 'Exact active Pull Request number.', [], true),
      flag('expected_base', '--expected-base <branch>', 'string', 'Approved Pull Request base branch.', [], true),
      flag('expected_state', '--expected-state <state>', 'enum', 'Must be ELIGIBLE_FOR_FOUNDER_REVIEW.', ['ELIGIBLE_FOR_FOUNDER_REVIEW'], true),
      flag('expected_old_head', '--expected-old-head <full-sha>', 'full_sha', 'Immutable Review 1 head.', [], true),
      flag('expected_new_head', '--expected-new-head <full-sha>', 'full_sha', 'Founder-authorized live correction head.', [], true),
      flag('expected_review_cycle', '--expected-review-cycle <number>', 'positive_integer', 'Existing review cycle; do not increment.', [], true),
      flag('expected_full_review_count', '--expected-full-review-count <number>', 'positive_integer', 'Existing full-review count; do not reset.', [], true),
      flag('authorization_comment', '--authorization-comment <id>', 'positive_integer', 'Immutable Founder authorization comment.', [], true),
    ],
    trusted_derived_values: ['Founder identity configuration', 'live Task/PR/policy/head evidence', 'lease/CAS holder identity'],
    required_evidence: [
      'Founder authorization bound to the complete repository/Task/PR/base tuple.',
      'Old reviewed head and new authorized head are distinct full SHAs.',
      'Review counters and original RESULT/REVIEW_VERDICT identities.',
    ],
    reads: ['Founder authorization', 'Task/PR/comments/policy/head'],
    writes: ['state projection to FOUNDER_AUTHORIZED_CORRECTION'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is NO_OP_IDENTICAL_RETRY only when the exact old/new-head authorization projection is already FOUNDER_AUTHORIZED_CORRECTION.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMMAND', 'bemoat:agent:delivery', 'The bounded correction delivery is the only next mutation.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The exact Founder-authorized reopen projection is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Reopen one Founder-authorized correction head.',
        argv: [
          '284',
          '--repo',
          'boat1994/bemoat-web-starter',
          '--expected-pr',
          '285',
          '--expected-state',
          'ELIGIBLE_FOR_FOUNDER_REVIEW',
          '--expected-old-head',
          '<review-1-sha>',
          '--expected-new-head',
          '<correction-sha>',
          '--expected-review-cycle',
          '1',
          '--expected-full-review-count',
          '1',
          '--authorization-comment',
          '12345',
        ],
      },
    ],
    parser_owner: 'scripts/mission-control/workflows/reopen.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:reopen -- --help --json',
    last_validation_before_mutation: 'Re-read the live Issue/PR, exact old/new heads, policy, counters, and immutable Founder authorization immediately before the lease/CAS write.',
    post_write_readback: 'Re-read the Issue/PR/comments and verify FOUNDER_AUTHORIZED_CORRECTION, preserved old head/counters, and the complete authorization record.',
    legacy_classification_map: {
      REOPENED: 'SUCCESS',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),

  'bemoat:mission-control:review': contract({
    command: 'bemoat:mission-control:review',
    tier: 'A',
    entrypoint: 'scripts/mission-control-review.mjs',
    purpose: 'Publish one ordinary Full or Delta Review verdict.',
    operation: 'Validate review evidence and project a leased/CAS REVIEW_VERDICT transition.',
    accepted_pre_states: ['AWAITING_REVIEW_1', 'AWAITING_REVIEW_2', 'AWAITING_REVIEW_3'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
      flag('body_file', '--body-file <path>', 'path', 'Read the review body from this file.', [], true),
      flag('expected_state', '--expected-state <state>', 'enum', 'Expected managed review state.', ['AWAITING_REVIEW_1', 'AWAITING_REVIEW_2', 'AWAITING_REVIEW_3'], true),
      flag('review_type', '--review-type <type>', 'enum', 'Full or Delta review.', ['full', 'delta'], true),
      flag('expected_head', '--expected-head <full-sha>', 'full_sha', 'Exact reviewed PR head.', [], true),
    ],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
    ],
    trusted_derived_values: ['reviewer identity', 'live Task/PR/comment/check evidence', 'lease/CAS holder identity'],
    required_evidence: [
      'Canonical verdict body and review type.',
      'Exact PR/base/head/check evidence.',
      'Current managed state and review counters.',
    ],
    reads: ['verdict body', 'Task/PR/comments/checks'],
    writes: ['REVIEW_VERDICT comment', 'leased/CAS Issue state and counters'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'An identical retry is allowed only when the same review identity and exact head are already projected.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:dispatch', 'The resulting review state determines the next bounded dispatch or Founder gate.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The identical review verdict is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Publish a full review verdict.',
        argv: ['284', '--body-file', './review.md', '--expected-state', 'AWAITING_REVIEW_1', '--review-type', 'full', '--expected-head', '<full-sha>'],
      },
    ],
    parser_owner: 'scripts/mission-control-review.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:review -- --help --json',
    last_validation_before_mutation: 'Re-read the verdict, current state/counters, exact PR head, and live comment evidence immediately before the lease/CAS write.',
    post_write_readback: 'Re-read the REVIEW_VERDICT comment and managed state and confirm the exact review identity, counters, and resulting state.',
    legacy_classification_map: {
      REVIEWED: 'SUCCESS',
      RECOVERABLE_ROUTING_DRIFT: 'AMBIGUOUS_RESULT',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),

  'bemoat:mission-control:task-bootstrap': contract({
    command: 'bemoat:mission-control:task-bootstrap',
    tier: 'A',
    entrypoint: 'scripts/mission-control-task-create.mjs',
    purpose: 'Create and attest a Mission Control Task Issue from Founder authorization.',
    operation: 'Verify signed Actions identity and project the initial Task state and campaign link.',
    accepted_pre_states: ['NOT_STATEFUL'],
    required_inputs: [
      flag('founder_authorization_comment_id', '--founder-authorization-comment-id <id>', 'positive_integer', 'Immutable Founder authorization comment.', [], true),
    ],
    optional_flags: [
      flag('check', '--check', 'boolean', 'Validate without creating the Task Issue.'),
      environment('GITHUB_ACTIONS', 'boolean', 'Trusted GitHub Actions execution identity.', ['true']),
      environment('GITHUB_REPOSITORY', 'repository', 'Trusted Actions repository identity.'),
      environment('GITHUB_WORKFLOW', 'string', 'Trusted Actions workflow identity.'),
      environment('GITHUB_REF', 'string', 'Trusted Actions ref identity.'),
      environment('GITHUB_SHA', 'full_sha', 'Trusted Actions commit identity.'),
      environment('GITHUB_RUN_ID', 'positive_integer', 'Trusted Actions workflow run identity.'),
      environment('BEMOAT_TASK_BOOTSTRAP_SIGNING_KEY_ID', 'string', 'Trusted signing key identity.'),
      environment('BEMOAT_TASK_BOOTSTRAP_SIGNING_PRIVATE_KEY', 'string', 'Trusted signing material supplied only by Actions secret configuration.'),
    ],
    trusted_derived_values: [
      'Actions-derived workflow identity',
      'trusted-derived protected public key',
      'GitHub-derived campaign and Pull Request evidence',
    ],
    required_evidence: [
      'Founder-authorized signed authorization.',
      'Actions-derived trusted GitHub workflow identity and public key.',
      'GitHub-derived campaign/PR evidence for the Task bootstrap.',
    ],
    reads: ['signed authorization', 'workflow identity', 'public key', 'GitHub campaign/PR'],
    writes: ['Task Issue creation/state/attestation', 'campaign projection'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is identical only when the same authorization fingerprint and Task projection already exist.',
    },
    role_contracts: {
      FOUNDER_AUTHORIZATION: {
        required_bindings: [
          'schema_version',
          'status',
          'authority',
          'author_login',
          'comment_id',
          'immutable_comment_reference',
          'non_superseded',
          'superseded_by',
          'repository',
          'bundle_kind',
          'parent_issue',
          'pr',
          'exact_head',
          'reviewed_head',
          'base',
          'policy_source',
          'policy_source_sha',
          'protected_base_sha',
          'policy_version',
          'scope',
          'action'
        ],
        representation: 'raw_json_object',
        identity_requirements: 'Must be authored by a trusted Founder login.',
        scope_binding: 'task-initialization',
        action_binding: 'create-managed-task',
        canonical_example: `{
  "schema_version": 1,
  "status": "approved",
  "authority": "Founder",
  "author_login": "boat1994",
  "comment_id": "12345",
  "immutable_comment_reference": true,
  "non_superseded": true,
  "superseded_by": null,
  "repository": "boat1994/bemoat-web-starter",
  "bundle_kind": "task-bootstrap-genesis",
  "parent_issue": 262,
  "task_issue": null,
  "pr": 263,
  "exact_head": "d5f0d1edf86f0c0f94a4891558ae6fcea7bfb73f",
  "reviewed_head": "d5f0d1edf86f0c0f94a4891558ae6fcea7bfb73f",
  "base": "main",
  "policy_source": "docs/mission-control/mission-control-guide.md",
  "policy_source_sha": "f46f5de1d5ee17669c7c4663893164ffb835b339",
  "protected_base_sha": "f6ac355b98aa281dda2a49bcf2ddaeb279d8173d",
  "policy_version": "1.3.0",
  "scope": "task-initialization",
  "action": "create-managed-task",
  "comment_sha256": "..."
}`
      }
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMMAND', 'bemoat:mission-control:dispatch', 'The bootstrapped Task is ready for HANDOFF dispatch.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The identical Task bootstrap is already durable.'),
      },
    ],
    examples: [{ description: 'Bootstrap from a Founder authorization comment.', argv: ['--founder-authorization-comment-id', '12345'] }],
    parser_owner: 'scripts/mission-control-task-create.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:task-bootstrap -- --help --json',
    last_validation_before_mutation: 'Re-verify signed authorization, Actions identity, public key, and campaign/PR evidence immediately before Task creation.',
    post_write_readback: 'Read the created Task Issue, attestation, and campaign projection and confirm the exact authorization fingerprint.',
    legacy_classification_map: {
      CREATED: 'SUCCESS',
      RECOVERED: 'SUCCESS',
      IDEMPOTENT: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  }
}
