/** Mission Control routing policy ownership. */
import { ALL_MUTATING_COMMANDS } from './mission-control-routing-policy-primary.ts'

type RouteParams = {
  route_key: string
  observed_state: string | null
  evidence_case: string
  required_evidence_condition: string
  forbidden_evidence_condition: string
  permitted_operation: string | null
  canonical_command: string | null
  required_review_type: string | null
  expected_post_state_or_gate: string
  prohibited_commands?: string[]
  decision: string
  stop_condition?: string | null
}

function route({
  route_key,
  observed_state,
  evidence_case,
  required_evidence_condition,
  forbidden_evidence_condition,
  permitted_operation,
  canonical_command,
  required_review_type,
  expected_post_state_or_gate,
  prohibited_commands = [],
  decision,
  stop_condition = null,
}: RouteParams) {
  return {
    route_key,
    observed_state,
    evidence_case,
    required_evidence_condition,
    forbidden_evidence_condition,
    permitted_operation,
    canonical_command,
    required_review_type,
    expected_post_state_or_gate,
    prohibited_commands,
    decision,
    stop_condition,
  }
}

export function missionControlRecoveryRoutes() {
  return [
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/exact-merge-authorization-current-reviewed-head',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'exact-merge-authorization-current-reviewed-head',
    required_evidence_condition: 'Exact Founder merge authorization and current reviewed head are verified.',
    forbidden_evidence_condition: 'Head drift, stale authorization, competing authority, or reopen tuple.',
    permitted_operation: 'Execute the Founder-authorized merge completion bundle.',
    canonical_command: 'bemoat:mission-control:merge',
    required_review_type: null,
    expected_post_state_or_gate: 'DONE',
    prohibited_commands: ['bemoat:mission-control:reopen'],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/complete-founder-old-new-head-reopen-tuple',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'complete-founder-old-new-head-reopen-tuple',
    required_evidence_condition: 'Founder authorization binds the complete repository/Task/PR/base, old reviewed head, new live head, counters, and bounded correction scope.',
    forbidden_evidence_condition: 'Missing, stale, superseded, competing, or same old/new head evidence.',
    permitted_operation: 'Project the Founder-authorized reopen correction state only.',
    canonical_command: 'bemoat:mission-control:reopen',
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_AUTHORIZED_CORRECTION',
    prohibited_commands: ['bemoat:mission-control:merge'],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ANY_STATE/unauthorized-head-drift',
    observed_state: null,
    evidence_case: 'unauthorized-head-drift',
    required_evidence_condition: 'Live head differs from the authorized/reviewed head without a matching authorization.',
    forbidden_evidence_condition: 'A complete exact Founder authorization proving the drift is permitted.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'STOP',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'STOP',
    stop_condition: 'Stop with HEAD_DRIFT; obtain fresh authority and exact evidence before any mutation.',
  }),
  route({
    route_key: 'ANY_STATE/proven-routing-only-projection-drift',
    observed_state: null,
    evidence_case: 'proven-routing-only-projection-drift',
    required_evidence_condition: 'A failed canonical transport left a routing-only projection drift proven by authoritative live evidence.',
    forbidden_evidence_condition: 'Ordinary delivery/review/reopen/merge work, ambiguous evidence, or an unproved write outcome.',
    permitted_operation: 'Repair the routing projection only.',
    canonical_command: 'bemoat:mission-control:reconcile',
    required_review_type: null,
    expected_post_state_or_gate: 'Verified routing projection',
    prohibited_commands: [
      'bemoat:mission-control:reopen',
      'bemoat:mission-control:merge',
    ],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ANY_STATE/exact-quarantined-274-275-incident-tuple',
    observed_state: null,
    evidence_case: 'exact-quarantined-274-275-incident-tuple',
    required_evidence_condition: 'The exact pinned #274/#275 incident tuple and quarantined raw-review evidence are complete.',
    forbidden_evidence_condition: 'Any ordinary review tuple or mismatch in the pinned incident identity.',
    permitted_operation: 'Run exceptional recovery only.',
    canonical_command: 'bemoat:mission-control:recover-review',
    required_review_type: 'delta',
    expected_post_state_or_gate: 'AWAITING_REVIEW_2 projection from quarantined evidence',
    prohibited_commands: [],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ANY_STATE/absent-managed-state-unique-reconstruction',
    observed_state: null,
    evidence_case: 'absent-managed-state-unique-reconstruction',
    required_evidence_condition: 'The managed Task Issue has no state markers and one immutable, uniquely bound correction lineage reconstructs the canonical projection exactly.',
    forbidden_evidence_condition: 'Any valid, malformed, partial, ambiguous, superseded, conflicting, unsupported, or executed-adoption evidence.',
    permitted_operation: 'Recreate exactly one absent managed-state projection through the exceptional recovery transport.',
    canonical_command: 'bemoat:mission-control:recover-state',
    required_review_type: null,
    expected_post_state_or_gate: 'Trusted-derived historical managed state with finding adoption still pending.',
    prohibited_commands: [
      'bemoat:mission-control:reconcile',
      'bemoat:mission-control:recover-review',
      'bemoat:mission-control:adopt-finding',
    ],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ANY_STATE/absent-managed-state-review-eligibility-reconstruction',
    observed_state: null,
    evidence_case: 'absent-managed-state-review-eligibility-reconstruction',
    required_evidence_condition: 'The managed Task Issue has no state markers and one immutable RESULT, PR/base/head, protected-main policy, and required CI tuple uniquely reconstructs Review 1 eligibility; a predecessor RESULT additionally requires the exact bounded mechanical correction delta to the live head.',
    forbidden_evidence_condition: 'Any valid, malformed, partial, ambiguous, superseded, conflicting, current-head verdict, or non-exact CI evidence.',
    permitted_operation: 'Recreate exactly one absent AWAITING_REVIEW_1 projection without publishing review evidence.',
    canonical_command: 'bemoat:mission-control:recover-review-eligibility',
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — managed review writer retired',
    prohibited_commands: [
      'bemoat:mission-control:reconcile',
      'bemoat:mission-control:recover-state',
      'bemoat:mission-control:merge',
    ],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'DONE/exact-identical-merge-completion-retry',
    observed_state: 'DONE',
    evidence_case: 'exact-identical-merge-completion-retry',
    required_evidence_condition: 'The exact merge-completion bundle, merge commit, closed Issue, and campaign projection are already verified.',
    forbidden_evidence_condition: 'Any changed head, authorization, merge commit, or terminal projection.',
    permitted_operation: 'Verify the existing merge completion without mutation.',
    canonical_command: 'bemoat:mission-control:merge',
    required_review_type: null,
    expected_post_state_or_gate: 'NO_OP_IDENTICAL_RETRY',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'DONE/no-retry-request',
    observed_state: 'DONE',
    evidence_case: 'no-retry-request',
    required_evidence_condition: 'The terminal DONE projection is complete and no retry request is present.',
    forbidden_evidence_condition: 'Unverified or conflicting terminal evidence.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'COMPLETE',
    decision: 'COMPLETE',
  }),
  route({
    route_key: 'BLOCKED_EXTERNAL/state-conflict-or-migration-required',
    observed_state: 'BLOCKED_EXTERNAL',
    evidence_case: 'blocked-external-state-conflict-or-migration-required',
    required_evidence_condition: 'External evidence is unavailable or the managed state requires an unresolved migration.',
    forbidden_evidence_condition: 'A complete authoritative recovery path.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'STOP',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'STOP',
    stop_condition: 'Stop until external evidence, state conflict, or migration requirements are resolved.',
  }),
  route({
    route_key: 'STATE_CONFLICT/explicit-stop',
    observed_state: 'STATE_CONFLICT',
    evidence_case: 'explicit-state-conflict-stop',
    required_evidence_condition: 'Managed evidence is contradictory, duplicated, or otherwise non-authoritative.',
    forbidden_evidence_condition: 'A fresh exact evidence tuple that resolves the conflict.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'STOP',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'STOP',
    stop_condition: 'Stop with STATE_CONFLICT; do not select a fallback command.',
  }),
  route({
    route_key: 'STATE_MIGRATION_REQUIRED/explicit-stop',
    observed_state: 'STATE_MIGRATION_REQUIRED',
    evidence_case: 'unresolved-state-migration-required',
    required_evidence_condition: 'The managed state explicitly requires a reviewed migration.',
    forbidden_evidence_condition: 'An approved migration result and stable state projection.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'STOP',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'STOP',
    stop_condition: 'Stop until the required state migration is separately reviewed and complete.',
  }),
  route({
    route_key: 'ANY_STATE/malformed-stale-superseded-duplicated-competing-evidence',
    observed_state: null,
    evidence_case: 'malformed-stale-superseded-duplicated-competing-evidence',
    required_evidence_condition: 'Evidence is malformed, stale, superseded, duplicated, competing, ambiguous, or unknown.',
    forbidden_evidence_condition: 'One exact supported evidence tuple with no competing interpretation.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'STOP',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'STOP',
    stop_condition: 'Stop with STATE_CONFLICT; never select a fallback command.',
  }),
  route({
    route_key: 'NOT_STATEFUL/explicit-fast-unmanaged-role-comment',
    observed_state: 'NOT_STATEFUL',
    evidence_case: 'explicit-fast-unmanaged-role-comment',
    required_evidence_condition: 'The operation is explicitly authorized as a FAST/unmanaged role comment.',
    forbidden_evidence_condition: 'Any managed-state transition or canonical transport evidence.',
    permitted_operation: 'Validate or post the unmanaged role comment.',
    canonical_command: 'bemoat:issue:comment',
    required_review_type: null,
    expected_post_state_or_gate: 'COMPLETE',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'NOT_STATEFUL/explicit-authorized-starter-child-sync',
    observed_state: 'NOT_STATEFUL',
    evidence_case: 'explicit-authorized-starter-child-sync',
    required_evidence_condition: 'The starter/child sync operation is explicitly authorized and its transition gates are complete.',
    forbidden_evidence_condition: 'Managed Task state mutation or unapproved project-specific resource changes.',
    permitted_operation: 'Synchronize the approved boilerplate projection.',
    canonical_command: 'bemoat:boilerplate:sync',
    required_review_type: null,
    expected_post_state_or_gate: 'COMPLETE',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'NOT_STATEFUL/explicit-local-hook-install',
    observed_state: 'NOT_STATEFUL',
    evidence_case: 'explicit-local-hook-install',
    required_evidence_condition: 'The local hook-install operation is explicitly authorized.',
    forbidden_evidence_condition: 'Task-state or remote GitHub mutation evidence.',
    permitted_operation: 'Install local hooks.',
    canonical_command: 'bemoat:hooks:install',
    required_review_type: null,
    expected_post_state_or_gate: 'COMPLETE',
    decision: 'COMMAND',
  }),
  ]
}
