/** Mission Control routing policy ownership. */
export const ALL_MUTATING_COMMANDS: string[] = [
  'bemoat:boilerplate:sync',
  'bemoat:hooks:install',
  'bemoat:issue:comment',
  'bemoat:mission-control:adopt-finding',
  'bemoat:mission-control:authorize-founder',
  'bemoat:mission-control:dispatch',
  'bemoat:mission-control:merge',
  'bemoat:mission-control:merge-standard',
  'bemoat:mission-control:reconcile',
  'bemoat:mission-control:recover-review',
  'bemoat:mission-control:recover-state',
  'bemoat:mission-control:recover-review-eligibility',
  'bemoat:mission-control:reopen',
  'bemoat:mission-control:review',
  'bemoat:mission-control:task-bootstrap',
]

type RouteParams = {
  route_key: string
  observed_state: string | null
  evidence_case: string
  required_evidence_condition: string
  forbidden_evidence_condition: string
  permitted_operation: string | null
  canonical_command: string | null
  required_review_type: string | null
  expected_post_state_or_gate: string
  prohibited_commands?: string[]
  decision: string
  stop_condition?: string | null
}

function route({
  route_key,
  observed_state,
  evidence_case,
  required_evidence_condition,
  forbidden_evidence_condition,
  permitted_operation,
  canonical_command,
  required_review_type,
  expected_post_state_or_gate,
  prohibited_commands = [],
  decision,
  stop_condition = null,
}: RouteParams) {
  return {
    route_key,
    observed_state,
    evidence_case,
    required_evidence_condition,
    forbidden_evidence_condition,
    permitted_operation,
    canonical_command,
    required_review_type,
    expected_post_state_or_gate,
    prohibited_commands,
    decision,
    stop_condition,
  }
}

export function missionControlPrimaryRoutes() {
  return [
  route({
    route_key: 'no-task/founder-authorization-recording',
    observed_state: null,
    evidence_case: 'Founder authorization is present in the execution context but no immutable repository-owned comment is durable',
    required_evidence_condition: 'Authenticated GitHub actor is a trusted Founder and live protected-base/policy/Issue evidence is complete.',
    forbidden_evidence_condition: 'Caller-supplied identity, placeholder body, comment edit, conflicting comment, or uncertain POST/readback.',
    permitted_operation: 'Record one final raw JSON Founder authorization body and verify its returned immutable ID/readback.',
    canonical_command: 'bemoat:mission-control:authorize-founder',
    required_review_type: null,
    expected_post_state_or_gate: 'Durable immutable Founder authorization evidence',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'no-task/exact-task-bootstrap-founder-authorization-workflow-tuple',
    observed_state: null,
    evidence_case: 'exact-task-bootstrap-founder-authorization-workflow-tuple',
    required_evidence_condition: 'Signed Founder authorization, trusted Actions workflow identity, public key, and campaign/PR tuple are complete.',
    forbidden_evidence_condition: 'Any missing, stale, competing, or conflicting bootstrap identity/evidence.',
    permitted_operation: 'Create and attest the Task Issue.',
    canonical_command: 'bemoat:mission-control:task-bootstrap',
    required_review_type: null,
    expected_post_state_or_gate: 'READY',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'READY/valid-handoff-inputs',
    observed_state: 'READY',
    evidence_case: 'valid-handoff-inputs',
    required_evidence_condition: 'One canonical HANDOFF binds the Task, workflow mode, and required planning/implementation lineage.',
    forbidden_evidence_condition: 'Duplicate, stale, competing, or malformed HANDOFF evidence.',
    permitted_operation: 'Claim the delivery or approved correction dispatch.',
    canonical_command: 'bemoat:mission-control:dispatch',
    required_review_type: null,
    expected_post_state_or_gate: 'IN_PROGRESS or FOUNDER_AUTHORIZED_CORRECTION',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'IN_PROGRESS/retired-delivery-coordinator',
    observed_state: 'IN_PROGRESS',
    evidence_case: 'retired-delivery-coordinator',
    required_evidence_condition: 'The historical IN_PROGRESS projection is encountered after the delivery coordinator has been retired.',
    forbidden_evidence_condition: 'Any attempt to infer a replacement stateful delivery command or mutate the historical projection.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Stop at the Founder gate; the historical delivery coordinator is retired and no replacement stateful transport is authorized.',
  }),
  route({
    route_key: 'AWAITING_REVIEW_1/exact-full-review-evidence',
    observed_state: 'AWAITING_REVIEW_1',
    evidence_case: 'exact-full-review-evidence',
    required_evidence_condition: 'Exact full-review body, reviewer identity, PR/base/head/check, and Task lineage are complete.',
    forbidden_evidence_condition: 'Delta review, stale head, duplicate verdict, or competing review evidence.',
    permitted_operation: 'Publish one ordinary Full Review.',
    canonical_command: 'bemoat:mission-control:review',
    required_review_type: 'full',
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_1, ELIGIBLE_FOR_FOUNDER_REVIEW, or a blocking gate',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'CORRECTION_REQUIRED_1/founder-authorized-finding-adoption',
    observed_state: 'CORRECTION_REQUIRED_1',
    evidence_case: 'founder-authorized-finding-adoption',
    required_evidence_condition: 'An immutable Founder adopt-finding authorization and predecessor correction contract are complete for the live CORRECTION_REQUIRED_1 head.',
    forbidden_evidence_condition: 'Caller-supplied findings, superseded authorization, competing adoption comments, or head/base drift.',
    permitted_operation: 'Append exactly one Founder-authorized finding to the active correction contract.',
    canonical_command: 'bemoat:mission-control:adopt-finding',
    required_review_type: null,
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_1 with reconciled active correction-contract identity',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'AWAITING_REVIEW_2/exact-delta-review-evidence',
    observed_state: 'AWAITING_REVIEW_2',
    evidence_case: 'exact-delta-review-evidence',
    required_evidence_condition: 'Exact Delta Review body, finding dispositions, reviewed head, and Task lineage are complete.',
    forbidden_evidence_condition: 'Full review on a delta route, stale head, duplicate verdict, or competing evidence.',
    permitted_operation: 'Publish one ordinary Delta Review.',
    canonical_command: 'bemoat:mission-control:review',
    required_review_type: 'delta',
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_2, ELIGIBLE_FOR_FOUNDER_REVIEW, or a blocking gate',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'CORRECTION_REQUIRED_2/founder-authorized-finding-adoption',
    observed_state: 'CORRECTION_REQUIRED_2',
    evidence_case: 'founder-authorized-finding-adoption',
    required_evidence_condition: 'An immutable Founder adopt-finding authorization and predecessor correction contract are complete for the live CORRECTION_REQUIRED_2 head.',
    forbidden_evidence_condition: 'Caller-supplied findings, superseded authorization, competing adoption comments, or head/base drift.',
    permitted_operation: 'Append exactly one Founder-authorized finding to the active correction contract.',
    canonical_command: 'bemoat:mission-control:adopt-finding',
    required_review_type: null,
    expected_post_state_or_gate: 'CORRECTION_REQUIRED_2 with reconciled active correction-contract identity',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'AWAITING_REVIEW_3/exact-bounded-delta-review-evidence',
    observed_state: 'AWAITING_REVIEW_3',
    evidence_case: 'exact-bounded-delta-review-evidence',
    required_evidence_condition: 'Exact bounded Delta Review evidence and required finding verification are complete.',
    forbidden_evidence_condition: 'Full review, stale head, duplicate verdict, or competing evidence.',
    permitted_operation: 'Publish the bounded Delta Review.',
    canonical_command: 'bemoat:mission-control:review',
    required_review_type: 'delta',
    expected_post_state_or_gate: 'ELIGIBLE_FOR_FOUNDER_REVIEW or a blocking gate',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'AWAITING_REVIEW_3/exact-blocker-verification-evidence',
    observed_state: 'AWAITING_REVIEW_3',
    evidence_case: 'exact-blocker-verification-evidence',
    required_evidence_condition: 'The exact bounded blocker-verification evidence is complete.',
    forbidden_evidence_condition: 'Unrelated review, stale head, duplicate verdict, or competing evidence.',
    permitted_operation: 'Publish the bounded blocker-verification Delta Review.',
    canonical_command: 'bemoat:mission-control:review',
    required_review_type: 'blocker-verification',
    expected_post_state_or_gate: 'ELIGIBLE_FOR_FOUNDER_REVIEW or BLOCKED_FOR_FOUNDER_DECISION',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'FOUNDER_AUTHORIZED_CORRECTION/unconsumed-exact-authorization',
    observed_state: 'FOUNDER_AUTHORIZED_CORRECTION',
    evidence_case: 'unconsumed-exact-authorization',
    required_evidence_condition: 'One unconsumed exact Founder correction authorization binds the current head and bounded scope.',
    forbidden_evidence_condition: 'Consumed, superseded, competing, or head-drifted authorization.',
    permitted_operation: 'Dispatch the Founder-authorized correction.',
    canonical_command: 'bemoat:mission-control:dispatch',
    required_review_type: null,
    expected_post_state_or_gate: 'IN_PROGRESS',
    prohibited_commands: ['bemoat:mission-control:merge', 'bemoat:mission-control:reopen'],
    decision: 'COMMAND',
  }),
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/exact-merge-authorization-recording',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'exact-merge-authorization-recording',
    required_evidence_condition: 'A trusted Founder provides authorization for the complete repository/Task/PR/base and reviewed head.',
    forbidden_evidence_condition: 'Head drift, duplicate authorization, competing authority, or agent invocation.',
    permitted_operation: 'Record an immutable Founder merge authorization.',
    canonical_command: 'bemoat:mission-control:authorize-founder',
    required_review_type: null,
    expected_post_state_or_gate: 'ELIGIBLE_FOR_FOUNDER_REVIEW with an immutable merge authorization and receipt',
    decision: 'COMMAND',
  }),
  route({
    route_key: 'BLOCKED_FOR_FOUNDER_DECISION/missing-named-authorization',
    observed_state: 'BLOCKED_FOR_FOUNDER_DECISION',
    evidence_case: 'missing-named-authorization',
    required_evidence_condition: 'The blocking evidence is present but the exact named Founder authorization is absent.',
    forbidden_evidence_condition: 'Any agent-mutation authorization or competing authority.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Wait for the exact named Founder authorization; no agent mutation is permitted.',
  }),
  route({
    route_key: 'ELIGIBLE_FOR_FOUNDER_REVIEW/missing-merge-authorization',
    observed_state: 'ELIGIBLE_FOR_FOUNDER_REVIEW',
    evidence_case: 'missing-merge-authorization',
    required_evidence_condition: 'An eligible review result is complete but merge authorization is absent.',
    forbidden_evidence_condition: 'Any inferred, stale, competing, or non-Founder merge authority.',
    permitted_operation: null,
    canonical_command: null,
    required_review_type: null,
    expected_post_state_or_gate: 'FOUNDER_GATE — no agent mutation',
    prohibited_commands: ALL_MUTATING_COMMANDS,
    decision: 'FOUNDER_GATE',
    stop_condition: 'Wait for explicit Founder merge or reopen authorization; no agent mutation is permitted.',
  }),
  route({
    route_key: 'NOT_STATEFUL/standard-non-managed-founder-merge-completion',
    observed_state: 'NOT_STATEFUL',
    evidence_case: 'standard-non-managed-founder-merge-completion',
    required_evidence_condition: 'Merged policy and live Issue declarations prove explicit STANDARD eligibility with no managed-state block; exact Founder authorization, one active exact-target REVIEW_VERDICT, exact-head CI, mergeability, and policy/protected-base identities are complete.',
    forbidden_evidence_condition: 'Managed, ambiguous, non-STANDARD, stale, duplicate, competing, superseded, mismatched, or malformed evidence.',
    permitted_operation: 'Merge the exact Founder-authorized non-managed PR head and verify protected-base readback.',
    canonical_command: 'bemoat:mission-control:merge-standard',
    required_review_type: null,
    expected_post_state_or_gate: 'COMPLETE without managed-state mutation',
    prohibited_commands: ['bemoat:mission-control:merge'],
    decision: 'COMMAND',
    stop_condition: 'Stop fail-closed on any managed/ambiguous shape, evidence conflict, head drift, failed CI, unavailable readback, or uncertain merge outcome.',
  }),
]
}
