/** Mission Control command metadata ownership. */
import type { CommandMetadataDependencies } from './mission-control-command-metadata-deps.ts'

export function missionControlPrimaryCommands(dependencies: CommandMetadataDependencies) {
  const { contract, positional, flag, nextAction } = dependencies
  return {
  'bemoat:mission-control:authorize-founder': contract({
    command: 'bemoat:mission-control:authorize-founder',
    tier: 'A',
    entrypoint: 'scripts/mission-control-authorize-founder.mjs',
    purpose: 'MIGRATION-ONLY HISTORICAL: Record an immutable Founder authorization.',
    operation: 'MIGRATION-ONLY HISTORICAL: Validate Founder identity, exact head or policy source, and protected base, and project an immutable authorization and receipt.',
    accepted_pre_states: ['NOT_STATEFUL', 'EXISTING_REGISTERED_TASK', 'ELIGIBLE_FOR_FOUNDER_REVIEW', 'STANDARD_NON_MANAGED_ELIGIBLE'],
    required_inputs: [positional('issue_number', '<issue-number>', 'positive_integer', 'Target Issue receiving the Founder authorization.'), flag('scope', '--scope <scope>', 'enum', 'Authorization scope.', ['merge', 'task-bootstrap'], true)],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
    ],
    trusted_derived_values: ['authenticated actor identity', 'trusted Founder logins', 'live PR/base/head/policy evidence', 'branch reservation evidence'],
    required_evidence: ['Exact head, base, and policy identity when applicable.', 'Separate immutable receipt binding the returned authorization comment ID to its exact body SHA-256.', 'Authenticated GitHub actor must be a trusted Founder.', 'Live protected main ref.', 'For STANDARD/non-managed Issues: merged-policy eligibility, one active exact-target REVIEW_VERDICT, and its immutable comment ID.'],
    reads: ['Task/PR/state', 'live protected main', 'BEMOAT_FOUNDER_LOGINS action variable', 'Issue comments'], writes: ['immutable authorization comment', 'immutable receipt comment', 'leased/CAS Issue state'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'An identical retry is allowed only when the same exact authorization comment and receipt are already durable.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('FOUNDER_GATE', null, 'The custom merge wrappers are retired; stop for native GitHub authority reconstruction or the separately registered task-bootstrap route.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        condition: 'Managed Task Issue with valid managed state.',
        next_action: nextAction('FOUNDER_GATE', null, 'The identical authorization is durable, but no custom merge wrapper remains.'),
      },
      {
        classification: 'SUCCESS',
        condition: 'Explicit STANDARD/non-managed eligibility with no managed state.',
        next_action: nextAction('FOUNDER_GATE', null, 'The STANDARD authorization is durable; Context must reconstruct native GitHub merge authority and evidence.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        condition: 'Explicit STANDARD/non-managed eligibility with no managed state.',
        next_action: nextAction('FOUNDER_GATE', null, 'The identical STANDARD authorization is durable, but no custom merge wrapper remains.'),
      },
    ],
    examples: [
      {
        description: 'Authorize a merge for a Task Issue.',
        argv: ['284', '--scope', 'merge', '--repo', 'boat1994/bemoat-web-starter'],
      },
      { description: 'Authorize a task-bootstrap.', argv: ['383', '--scope', 'task-bootstrap', '--repo', 'boat1994/bemoat-web-starter'] },
    ],
    parser_owner: 'scripts/mission-control-authorize-founder.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:authorize-founder -- --help --json',
    last_validation_before_mutation: 'Re-read the Task Issue, policy lineage, protected base, and existing authorization comments immediately before the leased/CAS write.',
    post_write_readback: 'Re-read the Issue comments and confirm the projected immutable authorization identity and receipt.',
    legacy_classification_map: {
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
      RECORDED: 'SUCCESS',
    },
  }),
  'bemoat:mission-control:reconcile': contract({
    command: 'bemoat:mission-control:reconcile',
    tier: 'A',
    entrypoint: 'scripts/mission-control-reconcile.mjs',
    purpose: 'MIGRATION-ONLY HISTORICAL: Repair routing-only Mission Control projection drift.',
    operation: 'MIGRATION-ONLY HISTORICAL: Classify authoritative evidence and apply only a leased/CAS routing projection repair.',
    accepted_pre_states: [
      'READY',
      'IN_PROGRESS',
      'AWAITING_REVIEW_1',
      'CORRECTION_REQUIRED_1',
      'AWAITING_REVIEW_2',
      'CORRECTION_REQUIRED_2',
      'AWAITING_REVIEW_3',
      'FOUNDER_AUTHORIZED_CORRECTION',
      'BLOCKED_FOR_FOUNDER_DECISION',
      'ELIGIBLE_FOR_FOUNDER_REVIEW',
      'DONE',
      'BLOCKED_EXTERNAL',
      'STATE_CONFLICT',
      'STATE_MIGRATION_REQUIRED',
    ],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Managed Task Issue number.'),
    ],
    optional_flags: [
      flag('repository', '--repo <owner/repository>', 'repository', 'Repository containing the Task Issue.'),
    ],
    trusted_derived_values: ['canonical transport ownership', 'live evidence identity', 'lease/CAS holder identity'],
    required_evidence: ['Authoritative live evidence proves routing-only projection drift after a failed canonical transport.'],
    reads: ['Task/PR/comments/state/terminal evidence'],
    writes: ['routing-only Issue state projection via lease/CAS'],
    success_classifications: [
      'SUCCESS',
      'NO_OP_IDENTICAL_RETRY',
    ],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is identical only when the authoritative evidence and routing projection already agree.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The routing-only projection repair is verified.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'No routing projection repair remains necessary.'),
      },
    ],
    examples: [{ description: 'Reconcile routing-only projection drift.', argv: ['284', '--repo', 'boat1994/bemoat-web-starter'] }],
    parser_owner: 'scripts/mission-control-reconcile.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:reconcile -- --help --json',
    last_validation_before_mutation: 'Re-read the authoritative evidence and Task Issue body immediately before the routing-only lease/CAS write.',
    post_write_readback: 'Re-read the Task Issue and confirm only the permitted routing projection changed.',
    legacy_classification_map: {
      RECONCILED: 'SUCCESS',
      BOOKKEEPING_REPAIR: 'SUCCESS',
      TERMINAL_REPAIR: 'SUCCESS',
      DISPATCHED: 'SUCCESS',
      REVIEWED: 'SUCCESS',
      RECOVERABLE_ROUTING_DRIFT: 'AMBIGUOUS_RESULT',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),
  'bemoat:mission-control:recover-review': contract({
    command: 'bemoat:mission-control:recover-review',
    tier: 'A',
    entrypoint: 'scripts/mission-control-recover-review.mjs',
    purpose: 'MIGRATION-ONLY HISTORICAL: Quarantine only the exact approved #274/#275 raw-review incident.',
    operation: 'MIGRATION-ONLY HISTORICAL: Verify the pinned incident tuple and project its proven Review 2 result.',
    accepted_pre_states: ['AWAITING_REVIEW_2'],
    required_inputs: [
      positional('issue_number', '<issue-number>', 'positive_integer', 'Quarantined incident Task Issue number.'),
      flag('repository', '--repo <owner/repository>', 'repository', 'Exact starter repository.', [], true),
      flag('expected_pr', '--expected-pr <number>', 'positive_integer', 'Exact incident Pull Request number.', [], true),
      flag('expected_base', '--expected-base <branch>', 'string', 'Exact protected base branch.', [], true),
      flag('expected_state', '--expected-state <state>', 'enum', 'Expected incident managed state.', ['AWAITING_REVIEW_2'], true),
      flag('expected_head', '--expected-head <full-sha>', 'full_sha', 'Exact incident PR head.', [], true),
      flag('expected_review_cycle', '--expected-review-cycle <number>', 'positive_integer', 'Expected managed review cycle.', [], true),
      flag('expected_full_review_count', '--expected-full-review-count <number>', 'positive_integer', 'Expected full-review count.', [], true),
      flag('review_type', '--review-type <type>', 'enum', 'Exact recovery review type.', ['delta'], true),
      flag('issue_source_comment', '--issue-source-comment <id>', 'positive_integer', 'Pinned Task Issue source comment.', [], true),
      flag('pr_source_comment', '--pr-source-comment <id>', 'positive_integer', 'Pinned PR source comment.', [], true),
      flag('original_review_comment', '--original-review-comment <id>', 'positive_integer', 'Pinned original review comment.', [], true),
      flag('correction_result_comment', '--correction-result-comment <id>', 'positive_integer', 'Pinned correction RESULT comment.', [], true),
      flag('body_file', '--body-file <path>', 'path', 'Read recovery review body from this file.', [], true),
    ],
    required_evidence: [
      'Pinned #274/#275 repository, Issue, PR, base, state, head, and comment tuple.',
      'Executing checkout and policy identity.',
      'Quarantined raw-review evidence with no ordinary-review ownership.',
    ],
    reads: ['pinned policy/source/checkout', 'Task/PR/comments/checks'],
    writes: ['one quarantined REVIEW_VERDICT comment', 'leased/CAS state projection'],
    success_classifications: ['SUCCESS', 'NO_OP_IDENTICAL_RETRY'],
    retry_contract: {
      identical_retry: 'conditional',
      classification: 'NO_OP_IDENTICAL_RETRY',
      condition: 'A retry is identical only when the same quarantined recovery evidence and projection are already durable.',
    },
    next_action_rules: [
      {
        classification: 'SUCCESS',
        next_action: nextAction('COMPLETE', null, 'The exact incident recovery projection is verified.'),
      },
      {
        classification: 'NO_OP_IDENTICAL_RETRY',
        next_action: nextAction('COMPLETE', null, 'The exact incident recovery projection is already durable.'),
      },
    ],
    examples: [
      {
        description: 'Run the quarantined incident recovery route.',
        argv: [
          '274',
          '--repo',
          'boat1994/bemoat-web-starter',
          '--expected-pr',
          '275',
          '--expected-base',
          'main',
          '--expected-state',
          'AWAITING_REVIEW_2',
          '--expected-head',
          '<full-sha>',
          '--expected-review-cycle',
          '1',
          '--expected-full-review-count',
          '1',
          '--review-type',
          'delta',
          '--issue-source-comment',
          '<task-issue-comment-id>',
          '--pr-source-comment',
          '<pr-source-comment-id>',
          '--original-review-comment',
          '<original-review-comment-id>',
          '--correction-result-comment',
          '<correction-result-comment-id>',
          '--body-file',
          './review.md',
        ],
      },
    ],
    parser_owner: 'scripts/mission-control/workflows/recover-review.mjs',
    safe_help_invocation: 'pnpm run bemoat:mission-control:recover-review -- --help --json',
    last_validation_before_mutation: 'Verify the complete pinned #274/#275 tuple and quarantine boundary immediately before the state/comment writes.',
    post_write_readback: 'Re-read the quarantined comment and managed state and confirm no ordinary REVIEW_VERDICT path was used.',
    legacy_classification_map: {
      RECOVERED: 'SUCCESS',
      RECOVERABLE_ROUTING_DRIFT: 'AMBIGUOUS_RESULT',
      NO_OP: 'NO_OP_IDENTICAL_RETRY',
    },
  }),

  }
}
